"""init: create raw schema tables

Revision ID: e9827ae898f0
Revises: 
Create Date: 2026-07-16 10:05:17.036521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9827ae898f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create schemas before tables (idempotent for Docker which uses init_db.sql)
    op.execute("CREATE SCHEMA IF NOT EXISTS raw")
    op.execute("CREATE SCHEMA IF NOT EXISTS staging")
    op.execute("CREATE SCHEMA IF NOT EXISTS mart")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fred_indicators',
    sa.Column('series_id', sa.String(length=50), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('series_name', sa.String(length=255), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('value IS NOT NULL', name='chk_fred_value'),
    sa.PrimaryKeyConstraint('series_id', 'observation_date'),
    schema='raw'
    )
    op.create_index('idx_fred_indicators_date', 'fred_indicators', ['observation_date'], unique=False, schema='raw')
    op.create_table('lc_loans',
    sa.Column('loan_id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=True),
    sa.Column('loan_amnt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('funded_amnt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('term', sa.String(length=20), nullable=True),
    sa.Column('int_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('installment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('grade', sa.String(length=1), nullable=True),
    sa.Column('sub_grade', sa.String(length=5), nullable=True),
    sa.Column('emp_title', sa.String(length=255), nullable=True),
    sa.Column('emp_length', sa.String(length=50), nullable=True),
    sa.Column('home_ownership', sa.String(length=50), nullable=True),
    sa.Column('annual_inc', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('loan_status', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('addr_state', sa.String(length=2), nullable=True),
    sa.Column('dti', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('delinq_2yrs', sa.Integer(), nullable=True),
    sa.Column('earliest_cr_line', sa.Date(), nullable=True),
    sa.Column('inq_last_6mths', sa.Integer(), nullable=True),
    sa.Column('open_acc', sa.Integer(), nullable=True),
    sa.Column('pub_rec', sa.Integer(), nullable=True),
    sa.Column('revol_bal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('revol_util', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_acc', sa.Integer(), nullable=True),
    sa.Column('total_pymnt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_rec_prncp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_rec_int', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('recoveries', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('collection_recovery_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('last_pymnt_date', sa.Date(), nullable=True),
    sa.Column('last_pymnt_amnt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('application_type', sa.String(length=50), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('annual_inc >= 0', name='chk_annual_inc'),
    sa.CheckConstraint('dti >= 0', name='chk_dti'),
    sa.CheckConstraint('int_rate >= 0 AND int_rate <= 100', name='chk_int_rate'),
    sa.CheckConstraint('loan_amnt > 0', name='chk_loan_amnt'),
    sa.PrimaryKeyConstraint('loan_id'),
    schema='raw'
    )
    op.create_index('idx_lc_loans_addr_state', 'lc_loans', ['addr_state'], unique=False, schema='raw')
    op.create_index('idx_lc_loans_grade_sub', 'lc_loans', ['grade', 'sub_grade'], unique=False, schema='raw')
    op.create_index('idx_lc_loans_issue_date', 'lc_loans', ['issue_date'], unique=False, schema='raw')
    op.create_index('idx_lc_loans_status', 'lc_loans', ['loan_status'], unique=False, schema='raw')
    op.create_table('sec_financials',
    sa.Column('adsh', sa.String(length=20), nullable=False),
    sa.Column('tag', sa.String(length=256), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('cik', sa.BigInteger(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('form_type', sa.String(length=20), nullable=True),
    sa.Column('fy', sa.Integer(), nullable=True),
    sa.Column('fp', sa.String(length=10), nullable=True),
    sa.Column('value', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('adsh', 'tag', 'period'),
    schema='raw'
    )
    op.create_index('idx_sec_financials_cik_period', 'sec_financials', ['cik', 'period'], unique=False, schema='raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sec_financials_cik_period', table_name='sec_financials', schema='raw')
    op.drop_table('sec_financials', schema='raw')
    op.drop_index('idx_lc_loans_status', table_name='lc_loans', schema='raw')
    op.drop_index('idx_lc_loans_issue_date', table_name='lc_loans', schema='raw')
    op.drop_index('idx_lc_loans_grade_sub', table_name='lc_loans', schema='raw')
    op.drop_index('idx_lc_loans_addr_state', table_name='lc_loans', schema='raw')
    op.drop_table('lc_loans', schema='raw')
    op.drop_index('idx_fred_indicators_date', table_name='fred_indicators', schema='raw')
    op.drop_table('fred_indicators', schema='raw')
    # ### end Alembic commands ###
